mcq/urls.py
from django.urls import path
from . import views

app_name = 'mcq'
urlpatterns = [
    path('', views.index, name='index'),
    path('settings', views.settings, name='settings'),
]

mcqs/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('mcq.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logoutUser, name='logout'),
    path('loginUser/', views.loginUser, name='login-user'),
    path('signupUser/', views.signupUser, name='signup-user'),
]

mcq/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _

class EmailUserManager(BaseUserManager):

    def create_user(self, email, password=None, **kwargs):
        if not email:
            raise ValueError('Email field is required')
        email = self.normalize_email(email)
        user = self.model(email=email, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        return self.create_user(email, password, **extra_fields)

class EmailUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. ''Unselect this instead of deleting accounts.'
        ),
    )

    USERNAME_FIELD = 'email'
    objects = EmailUserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.get_full_name()

    def __str__(self):
        return self.email

mcq/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'mcqs/index.html', {})


@login_required(login_url='/signin/')
def settings(request):
    return render(request, 'mcqs/settings.html', {})

users/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.db.utils import IntegrityError
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages import get_messages
from .models import EmailUser as User


def signin(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    return render(request, 'users/signform.html', {'login': True})


def signup(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')

    return render(request, 'users/signform.html', {'signup': True})


@login_required(login_url='/signin/')
def settings(request):
    return render(request, 'users/settings.html', {})


def logoutUser(request):
    logout(request)
    return HttpResponseRedirect('/')


def loginUser(request):
    email = request.POST.get('email')
    password = request.POST.get('password')
    user = authenticate(email=email, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return JsonResponse({'message': 'success'})
        else:
            return JsonResponse({'message': 'inactive'})
    else:
        return JsonResponse({'message': 'invalid'})


def signupUser(request):
    email = request.POST.get('email')
    password = request.POST.get('password')
    try:
        user = User.objects.create_user(email, password)
        user.save()
    except IntegrityError:
        return JsonResponse({'message': 'invalid'})
    return JsonResponse({'message': 'success'})

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>MCQS</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://cdn.materialdesignicons.com/3.6.95/css/materialdesignicons.min.css" rel="stylesheet">

</head>
<body>
	<div class="header">
	    <div class="greeting">
			{% if user.is_authenticated %}
			<span style="color: red">坚持 努力 加油！</span>
			<span>Hi, {{user.email}}!</span>
			<a href="{% url 'mcq:settings' %}">Settings</a>
			<a href="{% url 'users:logout' %}">Logout</a>
			{% else %}
	        <span>Welcome!</span>
	        <a href="{% url 'users:signin' %}">Login</a>
	        <a href="{% url 'users:signup' %}">Sign Up</a>
			{% endif %}
	    </div>
	</div>
    {% block content %}
    {% endblock %}

	<div class="footer">
		<div class="center-text">
	        This is a temporary footer!
	    </div>
	</div>

	<script src="{% static 'js/base.js' %}"></script>

	{% block script %}
    {% endblock %}
</body>

templates/mcqs/index.html
{% extends "base.html" %}


{% block content %}
{% if user.is_authenticated %}
<div class="content">
    <div class="center-text">
        You are now logged in! &#128540;
    </div>

</div>
{% else %}
<div class="content">
    <div class="center-text">
        Please <a href="{% url 'users:signin' %}">login</a> or <a href="{% url 'users:signup' %}">sign up</a> to use this beautiful memo!
    </div>

</div>
{% endif %}
{% endblock %}

templates/mcqs/settings.html
{% extends "base.html" %}


{% block content %}
<div class="content">
    <div class="center-text">
        This is a temporary settings page! &#x1F605;
    </div>

</div>
{% endblock %}

templates/users/signform.html
{% extends "base.html" %}


{% block content %}
<div class="content">
    <div class="sign">
        <div class='sign-form centered'>
        <div class="form-header">
            <button id="login">Login</button><!--
         --><button id="signup">Sign Up</button>
        </div>
        <form class="centered" id="signin-form">
            {% csrf_token %}
            <div class="hr-sect">Login with Email</div>
            <div id="login-error" class="error-message"></div>
            <input type="text" name="email" id="login-email" placeholder="Enter Email Address">
            <input type="password" id="login-password" name="password" placeholder="Enter Password">
            <!-- <input type="submit" value="Login!"> -->
            <button type="button" id="login-btn">Login!</button>
        </form>
        <form class="centered" id="signup-form">
            {% csrf_token %}
            <div class="hr-sect">Sign up with Email</div>
            <div id="signup-error" class="error-message"></div>
            <input type="text" name="email" id="signup-email" placeholder="Enter Email Address">
            <input type="password" id="signup-password" name="password" placeholder="Enter Password">
            <input type="password" name="confirm" placeholder="Confirm Password">
            <!-- <input type="submit" value="Sign Up!"> -->
            <button type="button" id="signup-btn">Sign Up!</button>
        </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
    {% if login %}
    <script type="text/jscript">
        $('#login').click();
    </script>
    {% endif %}
    {% if signup %}
    <script type="text/jscript">
        $('#signup').click();
    </script>
    {% endif %}
    {% load static %}
    <script src="{% static 'js/ajax_auth.js' %}"></script>
{% endblock %}